---
title: "02_xanes_analysis"
format:
  html:
    fig-height: 7
    fig-width: 7
editor: visual
editor_options: 
  chunk_output_type: console
---

## Setup

```{r}
library(tidyverse)
library(gt)
source("source/read_mu_file.R")
source("source/read_many_mu_files.R")
source("source/theme_xas.R")
```

```{r}
xanes <- read_rds("cache/xanes_data_raw.RDS")

metadata <- readxl::read_excel("data/metadata_annotated.xlsx", na = "NA")
```

Join xanes data and metadata

```{r}
xanes_w_metadata <- xanes |> 
  left_join(metadata, by = join_by(filename))

saveRDS(xanes_w_metadata, file = "cache/xanes_w_metadata.rds")
writexl::write_xlsx(xanes_w_metadata, path = "cache/xanes_w_metadata.xlsx")
```

# Find E0 positions

Here we define E0 as the first point in the normalized spectrum that reaches 0.5 of the post-edge norm value `1`.

```{r}
e0s <- xanes_w_metadata |> 
  group_by(filename) |> 
  arrange(energy) |>  #make sure data is sorted along the energy
  filter(samnorm >= 0.5) |> # filter for points above 0.5 norm
  slice(1) |> # find the first point. this is our E0
  ungroup() |> 
  rename(e0 = energy, e0_abs = samnorm)

e0s_stds <- e0s |> 
  filter(!is_TLE, is_standard) |> 
  select(filename, compound, e0, e0_abs) |> 
  arrange(e0) |> # rank the e0s in ascending order
  mutate(offset = row_number()) 
```


## TLE

```{r}
xanes_TLE <- xanes_w_metadata |> 
  filter(is_TLE) |> 
  mutate(
    depth_str = paste(core_depth_m, "m"),
    depth_fct = as.factor(depth_str),
    depth_fct = fct_reorder(depth_fct, core_depth_m, .na_rm = FALSE)
  ) |> 
  arrange(depth_fct)
```

### Find peak position of TLE standards


```{r}
xanes_TLE_STD_max <- xanes_TLE |> 
  filter(is_standard) |> 
  group_by(compound) |> 
  # find the eV that is max samnorm
  summarise(
    energy = energy[which.max(samnorm)],
    samnorm = max(samnorm)
    ) |> 
  ungroup()
```

### Plot TLE XANES

```{r}

p_tle_standards <- xanes_TLE |> 
  filter(compound != "BA1B_280") |> 
  filter(is_standard) |> 
  mutate(header = "Standards") |> 
  ggplot(
    aes(
      x = energy,
      y = samnorm,
      color = compound,
      fill = compound
    )
  ) +
  scale_fill_brewer(palette = "Set1") +
  scale_color_brewer(palette = "Set1") +
  geom_vline(
    data = xanes_TLE_STD_max,
    aes(xintercept = energy,
        color = compound),
    linewidth = 0.25,
    show.legend = FALSE
  ) +
  geom_line(linewidth = 1) +
  coord_cartesian(xlim = c(2465, 2505)) +
  ggprism::annotation_ticks(sides = "tb") +
  facet_wrap(vars(header)) +
  labs(
    x = "Energy (eV)",
    y = "Normalized Absorption",
    color = "Standard Compound"
  ) +
  theme_xas() +
  theme()
p_tle_standards

# cowplot::save_plot(
#   plot = p_tle_standards,
#   filename = "fig_output/tle_standards.pdf",
#   base_height = 6,
#   base_width = 9
# )
```

Plot TLE Samples

```{r}
p_ba1b <- xanes_TLE |> 
  filter(!is_standard) |> 
  filter(!is_TLE_blank) |> 
  filter(!is_GFF) |> 
  filter(core == "BA1B") |> 
  ggplot(
    aes(
      x = energy,
      y = samnorm,
      color = depth_fct
    )
  ) +
  geom_vline(
    data = xanes_TLE_STD_max,
    aes(xintercept = energy),
    color = "gray",
    linewidth = 0.25
  ) +
  geom_line(linewidth = 1) +
  coord_cartesian(xlim = c(2465, 2505)) +
  scale_color_viridis_d(direction = -1, end = 0.9) +
  facet_wrap(vars(core)) +
  ggprism::annotation_ticks(sides = "tb") +
  labs(
    x = "Energy (eV)",
    y = "Normalized Absorption",
    color = "Core Depth"
  ) +
  theme_xas() +
  theme()
p_ba1b
```

```{r}
p_ba4a <- xanes_TLE |> 
  filter(!is_standard) |> 
  filter(!is_TLE_blank) |> 
  filter(!is_GFF) |> 
  filter(core == "BA4A") |> 
  ggplot(
    aes(
      x = energy,
      y = samnorm,
      color = depth_fct
    )
  ) +
  geom_vline(
    data = xanes_TLE_STD_max,
    aes(xintercept = energy),
    color = "gray",
    linewidth = 0.25
  ) +
  geom_line(linewidth = 1) +
  coord_cartesian(xlim = c(2465, 2505)) +
  scale_color_viridis_d(direction = -1, end = 0.9) +
  facet_wrap(vars(core)) +
  ggprism::annotation_ticks(sides = "tb") +
  labs(
    x = "Energy (eV)",
    y = "Normalized Absorption",
    color = "",
  ) +
  theme_xas() +
  theme()
p_ba4a
```

```{r}
p_ba3a <- xanes_TLE |> 
  filter(!is_standard) |> 
  filter(!is_TLE_blank) |> 
  filter(!is_GFF) |> 
  filter(core == "BA3A") |> 
  ggplot(
    aes(
      x = energy,
      y = samnorm,
      color = depth_fct
    )
  ) +
  geom_vline(
    data = xanes_TLE_STD_max,
    aes(xintercept = energy),
    color = "gray",
    linewidth = 0.25
  ) +
  geom_line(linewidth = 1) +
  coord_cartesian(xlim = c(2465, 2505)) +
  scale_color_viridis_d(direction = -1, end = 0.9) +
  facet_wrap(vars(core)) +
  ggprism::annotation_ticks(sides = "tb") +
  labs(
    x = "Energy (eV)",
    y = "Normalized Absorption",
    color = ""
  ) +
  theme_classic() +
  theme(
    panel.background = element_rect(color = "black"),
    strip.background = element_rect(color = "#464747", fill = "#464747"),
    strip.text = element_text(color = "white"),
    axis.ticks.x = element_blank()
  )
p_ba3a
```

```{r}
p_tle_blanks <- xanes_TLE |> 
  filter(is_TLE_blank) |> 
  mutate(header = "Controls") |> 
  ggplot(
    aes(
      x = energy,
      y = samnorm,
      color = compound
    )
  ) +
  geom_vline(
    data = xanes_TLE_STD_max,
    aes(xintercept = energy),
    linewidth = 0.25,
    color = "gray",
    show.legend = FALSE
  ) +
  geom_line(linewidth = 1) +
  coord_cartesian(xlim = c(2465, 2505)) +
  ggprism::annotation_ticks(sides = "tb") +
  facet_wrap(vars(header)) +
  labs(
    x = "Energy (eV)",
    y = "Normalized Absorption",
    color = "Control"
  ) +
  theme_xas() +
  theme()
p_tle_blanks
```

```{r}
p_tle_combined <- cowplot::plot_grid(p_ba1b, p_ba4a, p_ba3a, p_tle_standards, p_tle_blanks, ncol = 1, align = "hv", axis = "b")

p_tle_combined

# cowplot::save_plot(
#   filename = "fig_output/tle_combined_plot.pdf",
#   plot = p_tle_combined,
#   base_height = 12,
#   base_width = 8
# )
```

## Mineral Standards

```{r}
xanes_stds <- xanes_w_metadata |> 
  filter(!is_TLE, is_standard)

```

### Plot mineral standards

```{r}
xanes_stds |> 
  left_join(e0s_stds, by = join_by(filename, compound)) |> 
  mutate(compound = fct_reorder(as.factor(compound), offset)) |> 
  arrange(offset) |> 
  ggplot(
    aes(
      x = energy,
      y = samnorm + offset,
      color = compound,
      fill = compound
    )
  ) +
  geom_line(linewidth = 1, show.legend = FALSE) +
  geom_point(
    data = e0s_stds,
    aes(
      x = e0, y = e0_abs + offset
    ),
    size = 3, color = "black", shape = 21
  ) +
  geom_text(
    data = e0s_stds,
    aes(label = compound, y = e0_abs + offset + 1),
    x = 2495, color = "black", size = 3, hjust = 1
  ) +
  ggprism::annotation_ticks(sides = "tb") +
  scale_color_viridis_d(end = 0.85) +
  scale_fill_viridis_d(end = 0.85) +
  coord_cartesian(xlim = c(2465, 2495)) +
  labs(
    x = "Energy (eV)",
    y = "",
    color = ""
  ) +
  theme_bw() +
  theme(
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    axis.text.y = element_blank()
  ) +
  guides(color = guide_legend(reverse=TRUE),
         fill = guide_legend(reverse=TRUE))
```


# Reaction products

```{r}
xanes_rxns <- xanes_w_metadata |> 
  filter(str_detect(compound, "Brucite"))
```


```{r}
# Plot
xanes_rxns |> 
  mutate(offset = case_when(
    str_detect(compound, "Sulfide") ~ 1,
    str_detect(compound, "Thio") ~ 2
  )) |> 
  ggplot(
    aes(x = energy, y = samnorm + offset, color = compound)
  ) +
  geom_line() +
  ggprism::annotation_ticks(sides = "tb") +
  theme_xas() +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank()
  )

# compare to tochilinite
tochilinite_xas <- xanes_w_metadata |> filter(compound == "Sodium thiosulfate")

xanes_rxns |> 
  bind_rows(tochilinite_xas) |> 
  mutate(offset = case_when(
    compound == "Brucite + Sulfide Product" ~ 2,
    compound == "Brucite + Thiosulfate Product" ~ 1,
    compound == "Sodium thiosulfate" ~ 0
  )) |> 
  ggplot(
    aes(x = energy, y = samnorm + offset/2, color = compound)
  ) +
  geom_line() +
  ggprism::annotation_ticks(sides = "tb") +
  coord_cartesian(xlim = c(2460, 2500)) +
  theme_xas() +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank()
  )

```


# Core powders

```{r}
xanes_core_powders <- xanes_w_metadata |> 
  filter(is_powder, !is_standard, !is.na(core))
```

```{r}
xanes_core_powders |> 
  ggplot(
    aes(
      x = energy, y = samnorm,
      group = filename, color = as.factor(core_depth_m)
    )
  ) +
  geom_line() +
  facet_wrap(vars(core)) +
  ggprism::annotation_ticks(sides = "tb") +
  theme_xas()
```

